### ISSUE TITLE
Can't send buffer to gnuplot under Windows

### ISSUE THREAD

**Issue by rhstanton** [emacsorphanage/gnuplot#15]
I just installed gnuplot 4.6 in Windows Vista, and then installed gnuplot-mode. Unfortunately, when I try to send the buffer to gnuplot, only the first line of the buffer seems to get sent (looking at the gnuplot window). I'm using pgnuplot.exe as my executable, but I've also tried gnuplot.exe and this doesn't help.

Note: If I use the latest version of gnuplot-mode.el by Mike McCourt, with the same gnuplot setup, it sends the whole buffer to gnuplot just fine, so the gnuplot setup does work (in theory).

Thanks.

**Comment by Arjay-El** [comment]
Gnuplot V5 no longer includes pgnuplot.exe. I am now back to C-g to end the attempted plot session with no output. Tried a straightforward sub with wgnuplot but that just opened the console and I could not have a plot returned to my org doc. Is there a workaround for this with the disappearance of pgnuplot?

**Comment by bruceravel** [comment]
I don't normally do my gnuplotting on windows, but ... Does the `gnuplot.exe` executable not work?

**Comment by Arjay-El** [comment]
Gnuplot 5.x works fine standalone on Windows 10-64b, its a great program. I am just try to create plots inline in Emacs 25.1. I have enabled it with org-babel and am following the method listed above. I tried using gnuplot as is to replace pgnuplot. That provides a message saying the plot is complete but Emacs does not respond until you C-g out and no plot is created. I substituted wgnuplot in place of pgnuplot and it opens a console window. I can run the script in that window but it does not return the plot to Emacs. I have to work in windows so linux is not an option. I posted the message to see if anyone had an updated advice/workarounds. Thanks for your reply, appreciated. (PS: I am not a  programmer, just an end user using Emacs for research papers which is why I'd love to have gnuplot work inline on Emacs/Windows.).

**Comment by zzg20082009** [comment]
Emacs run gnuplot.exe as a sub process, But in that sub process CACHES the input and output, So the input or output weren't reach at the final destination. I don't think that can be solved. :(
https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/Subprocess-hang.html

**Comment by AforAnonymous** [comment]
>I don't think that can be solved

Why not?

**Comment by theldoria** [comment]
Is there any progress in work?

Btw, installing `gnuplot-mode` from MELPA (as suggested by @joddie) and changing `(comint-send-input)` to `(comint-send-input nil 1)` (as suggested by @Harry79) solved my `org-mode` export issues.

**Comment by conao3** [comment]
Windows is not supported for now. please ref #33
