### ISSUE TITLE
Nested loop: weird cursor behavior

### ISSUE THREAD

**Issue by vjaunet** [emacsorphanage/gnuplot#35]
Hello,
I am experiencing an issue with nested for loops and the behavior of the return key. A minimal script is
```
do for [i=1:10]{
    do for [j=1:10]{
      plot sin(x) 
  }
}
```
If I place the cursor at the end of the second or third line and press tab or enter, the cursor jumps directly at the last curly brace.
I am using GNU Emacs 25.2.1 and gnuplot-mode from Melpa.

Regards,
Vincent

**Comment by madchemiker** [comment]
I have the same problem.

**Work around:**
Use normal spaces for tab.
The following lines in .emacs works fine for me (on Emacs 25.3.1).

    (add-hook 'gnuplot-mode-hook
    	  '(lambda ()
    	     (setq indent-tabs-mode nil)))

If you want to edit an existing file, you must replace TAB-chars with spaces first.
(To do this you can do "C-x h" (mark-whole-buffer), then "M-x untabify".)

**Cause of the problem:**
A function (gnuplot-indent-line) in gnuplot.el does not treat TAB-chars correctly.
If indent level > 8 (e.g. 12) and TAB-chars exists, (forward-char 12) does not work as expected
(because TAB-char will be counted as 1 character, not 8).

**Comment by madchemiker** [comment]
Better solution: Apply this patch.
(I hope) you can use TAB-char for indentation without any problem.

https://gist.github.com/madchemiker/c55224939af658cebb9c95efe1f61042

**Comment by conao3** [comment]
Thanks @madchemiker!
